Dir debian fixes
DOMjudge/domjudge-packaging pull request #112
Opened 2021-11-28 13:56 UTC by vmcj

2021-11-28 14:08 UTC, Dup4 approved these changes

2021-11-29 08:26 UTC, thijskh requested changes
Does not work, this is the result.

What is the intended benefit?

```
./configure \
	--enable-fhs \
	--prefix=/usr \
	--sysconfdir=/etc \
	--localstatedir=/var \
	\
	--with-domjudge_docdir=\"/share/doc/domjudge-doc \
	\
	--with-domserver_libdir=\"/share/domjudge \
	--with-domserver_libvendordir=\"/share/domjudge/lib/vendor \
	--with-domserver_webappdir=\"/share/domjudge/webapp \
	--with-domserver_logdir=/var/log/domjudge/domserver \
	\
	--with-judgehost_bindir=\"/sbin \
	--with-judgehost_libdir=\"/share/domjudge \
	--with-judgehost_libjudgedir=\"/lib/domjudge \
	--with-judgehost_chrootdir=/var/lib/domjudge/chroot \
	--with-judgehost_logdir=/var/log/domjudge/judgehost \
	\
```

2021-11-29 09:17 UTC, vmcj commented
> Does not work, this is the result.
> 
> What is the intended benefit?
> 
> ```
> ./configure \
> 	--enable-fhs \
> 	--prefix=/usr \
> 	--sysconfdir=/etc \
> 	--localstatedir=/var \
> 	\
> 	--with-domjudge_docdir=\"/share/doc/domjudge-doc \
> 	\
> 	--with-domserver_libdir=\"/share/domjudge \
> 	--with-domserver_libvendordir=\"/share/domjudge/lib/vendor \
> 	--with-domserver_webappdir=\"/share/domjudge/webapp \
> 	--with-domserver_logdir=/var/log/domjudge/domserver \
> 	\
> 	--with-judgehost_bindir=\"/sbin \
> 	--with-judgehost_libdir=\"/share/domjudge \
> 	--with-judgehost_libjudgedir=\"/lib/domjudge \
> 	--with-judgehost_chrootdir=/var/lib/domjudge/chroot \
> 	--with-judgehost_logdir=/var/log/domjudge/judgehost \
> 	\
> ```

I assumed so, the intended benefit was that:
- shellcheck would not complain
- We get less change of wrong invocations,

but as the variable is filled by the one making the packages excluding the rule will make more sense.

2021-11-29 09:59 UTC, eldering commented
> > Does not work, this is the result.
> > What is the intended benefit?
[...] 
> I assumed so, the intended benefit was that:
> 
>     * shellcheck would not complain,
> 
>     * we get less possible ways to invoke the script in the wrong way,
> 
> 
> but as the variable is filled by the one making the packages excluding the rule will make more sense.

This is not a shell script but a Makefile, so the whole file should be ignored.

2021-11-29 16:09 UTC, closed without merging